version: '2.1'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    container_name: 'elasticsearch'
    volumes:
      - ./elasticsearch/settings/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      esnet:
        aliases:
          - elasticsearch:elasticsearch
    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.0
    container_name: 'kibana'
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - esnet
    links:
      - elasticsearch:elasticsearch
  logstash:
    image: docker.elastic.co/logstash/logstash:5.4.0
    container_name: logstash
    volumes:
      - ./logstash/logs:/opt/logs
      - ./logstash/pipeline:/usr/share/logstash/pipeline/
      - ./logstash/settings/logstash.yml:/usr/share/logstash/config/logstash.yml
    links:
      - elasticsearch:elasticsearch
    networks:
      - esnet
networks:
  esnet: